<?php
require_once(__DIR__.'/widgets.php');
require_once(__DIR__.'/adminbar.php');
require_once(__DIR__.'/vt_resize.php');
require_once(__DIR__.'/duplicate_post.php');
require_once(__DIR__.'/svg_mimes.php');
require_once(__DIR__.'/post_thumbnails.php');
require_once(__DIR__.'/prev_next_post.php');
require_once(__DIR__.'/projecten.php');
require_once(__DIR__.'/hero.php');
require_once(__DIR__.'/team.php');
require_once(__DIR__.'/makemyblock.php');
